theme: jekyll-theme-cayman
show_downloads: true
github:
  Win: https://github.com/xchapter7x/haikube/releases/download/v0.3.0/hk.exe
  OSX: https://github.com/xchapter7x/haikube/releases/download/v0.3.0/hk_osx
  Linux: https://github.com/xchapter7x/haikube/releases/download/v0.3.0/hk_unix
