# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10
    working_directory: /go/src/github.com/xchapter7x/haikube
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: make dep 
      - run: make test 
      - run: make build
